name: FormikoUsualTool
author: "HydrolienF"
description: 'Execute code with args'
branding:
  icon: 'play'
  color: 'orange'

on:
  pull_request:
    branches: [master]
    types: [closed]


inputs:
  args:
    description: 'args to use'
    required: true

env:
  JAVA_VERSION: '18'
  JAVA_DISTRIBUTION: 'temurin'


runs:
  using: "composite"
  steps:

  - uses: actions/setup-java@v3
    with:
      distribution: ${{ env.JAVA_DISTRIBUTION }}
      java-version: ${{ env.JAVA_VERSION }}

  - name: Execute with args
    shell: pwsh
    run: |
      cd ${{ github.action_path }}
      mvn -ntp package "-Dmaven.test.skip"
      cd ~
      mv ${{ github.action_path }}/target/*with-dependencies.jar u.jar
      java -jar u.jar ${{ inputs.args }}
      echo ================================
      ls
