name: Javadoc

on:
  pull_request:
    branches: [master]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  updateJavadoc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 18
    - name: Javadoc update
      run: |
        mvn compile exec:java -Dargs="javadocHeader"
        mvn javadoc:javadoc
    - name: Commit
      run: |
        if [[ `git status --untracked-files=no --porcelain docs/` != "\n" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase true
          git add docs/
          git commit -m "Auto javadoc update"
          git fetch
          git pull
          git push
        fi
