# This workflow will release a new version of Usual

name: Publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: download Version-Tool
      run: |
        wget https://github.com/HydrolienF/Version-Tool/archive/refs/tags/0.5.7.zip
        unzip 0.5.7.zip
        mv Version-Tool-0.5.7/*.sh .

    - name: Version-Tool
      uses: HydrolienF/Version-Tool@0.5.7
      id: version

    - name: update version.md
      run: echo ${{ steps.version.outputs.version }} > version.md

    - name: to .jar
      run: |
        mvn -ntp package
        mv target/FormikoUsual-${{ steps.version.outputs.version }}-jar-with-dependencies.jar FormikoUsual${{ steps.version.outputs.version }}.jar


    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: FormikoUsual${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload .jar artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: FormikoUsual${{ steps.version.outputs.version }}.jar
        asset_name: FormikoUsual${{ steps.version.outputs.version }}.jar
        asset_content_type: application/java-archive
